host=127.0.0.1
port=6379
password=
database=0
connect_timeout_ms=1000
# 用户在线状态的 “存活时间” 为 120 秒,后台维护线程(主线程)每隔几十秒就会遍历所有活跃连接，执行 EXPIRE 刷新这个键的生存时间。
# 如果服务端宕机，那么redis120s后删除该键，那么用户下线
presence_ttl_seconds=120
# 所有键都会加上前缀 chatroom:
key_prefix=chatroom
# 追加PID后缀，放置多个实例重复处理同一个任务
server_name=chat-server
