// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chat_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chat_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chat_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chat_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_5fmessage_2eproto;
namespace chatroom {
namespace v7 {
class ChatMessagePayload;
struct ChatMessagePayloadDefaultTypeInternal;
extern ChatMessagePayloadDefaultTypeInternal _ChatMessagePayload_default_instance_;
}  // namespace v7
}  // namespace chatroom
PROTOBUF_NAMESPACE_OPEN
template<> ::chatroom::v7::ChatMessagePayload* Arena::CreateMaybeMessage<::chatroom::v7::ChatMessagePayload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chatroom {
namespace v7 {

enum ChatMessageType : int {
  CHAT_MESSAGE_TYPE_UNSPECIFIED = 0,
  PUBLIC = 1,
  PRIVATE = 2,
  ChatMessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ChatMessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ChatMessageType_IsValid(int value);
constexpr ChatMessageType ChatMessageType_MIN = CHAT_MESSAGE_TYPE_UNSPECIFIED;
constexpr ChatMessageType ChatMessageType_MAX = PRIVATE;
constexpr int ChatMessageType_ARRAYSIZE = ChatMessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChatMessageType_descriptor();
template<typename T>
inline const std::string& ChatMessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ChatMessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ChatMessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ChatMessageType_descriptor(), enum_t_value);
}
inline bool ChatMessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ChatMessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ChatMessageType>(
    ChatMessageType_descriptor(), name, value);
}
// ===================================================================

class ChatMessagePayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chatroom.v7.ChatMessagePayload) */ {
 public:
  inline ChatMessagePayload() : ChatMessagePayload(nullptr) {}
  ~ChatMessagePayload() override;
  explicit PROTOBUF_CONSTEXPR ChatMessagePayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatMessagePayload(const ChatMessagePayload& from);
  ChatMessagePayload(ChatMessagePayload&& from) noexcept
    : ChatMessagePayload() {
    *this = ::std::move(from);
  }

  inline ChatMessagePayload& operator=(const ChatMessagePayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatMessagePayload& operator=(ChatMessagePayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatMessagePayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatMessagePayload* internal_default_instance() {
    return reinterpret_cast<const ChatMessagePayload*>(
               &_ChatMessagePayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatMessagePayload& a, ChatMessagePayload& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatMessagePayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatMessagePayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatMessagePayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatMessagePayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatMessagePayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatMessagePayload& from) {
    ChatMessagePayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatMessagePayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chatroom.v7.ChatMessagePayload";
  }
  protected:
  explicit ChatMessagePayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSenderUsernameFieldNumber = 2,
    kRecipientUsernameFieldNumber = 3,
    kContentFieldNumber = 4,
    kCreatedAtUnixMsFieldNumber = 5,
    kTypeFieldNumber = 1,
  };
  // string sender_username = 2;
  void clear_sender_username();
  const std::string& sender_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_username();
  PROTOBUF_NODISCARD std::string* release_sender_username();
  void set_allocated_sender_username(std::string* sender_username);
  private:
  const std::string& _internal_sender_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_username(const std::string& value);
  std::string* _internal_mutable_sender_username();
  public:

  // string recipient_username = 3;
  void clear_recipient_username();
  const std::string& recipient_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_recipient_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_recipient_username();
  PROTOBUF_NODISCARD std::string* release_recipient_username();
  void set_allocated_recipient_username(std::string* recipient_username);
  private:
  const std::string& _internal_recipient_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_recipient_username(const std::string& value);
  std::string* _internal_mutable_recipient_username();
  public:

  // string content = 4;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // int64 created_at_unix_ms = 5;
  void clear_created_at_unix_ms();
  int64_t created_at_unix_ms() const;
  void set_created_at_unix_ms(int64_t value);
  private:
  int64_t _internal_created_at_unix_ms() const;
  void _internal_set_created_at_unix_ms(int64_t value);
  public:

  // .chatroom.v7.ChatMessageType type = 1;
  void clear_type();
  ::chatroom::v7::ChatMessageType type() const;
  void set_type(::chatroom::v7::ChatMessageType value);
  private:
  ::chatroom::v7::ChatMessageType _internal_type() const;
  void _internal_set_type(::chatroom::v7::ChatMessageType value);
  public:

  // @@protoc_insertion_point(class_scope:chatroom.v7.ChatMessagePayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recipient_username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    int64_t created_at_unix_ms_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatMessagePayload

// .chatroom.v7.ChatMessageType type = 1;
inline void ChatMessagePayload::clear_type() {
  _impl_.type_ = 0;
}
inline ::chatroom::v7::ChatMessageType ChatMessagePayload::_internal_type() const {
  return static_cast< ::chatroom::v7::ChatMessageType >(_impl_.type_);
}
inline ::chatroom::v7::ChatMessageType ChatMessagePayload::type() const {
  // @@protoc_insertion_point(field_get:chatroom.v7.ChatMessagePayload.type)
  return _internal_type();
}
inline void ChatMessagePayload::_internal_set_type(::chatroom::v7::ChatMessageType value) {
  
  _impl_.type_ = value;
}
inline void ChatMessagePayload::set_type(::chatroom::v7::ChatMessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:chatroom.v7.ChatMessagePayload.type)
}

// string sender_username = 2;
inline void ChatMessagePayload::clear_sender_username() {
  _impl_.sender_username_.ClearToEmpty();
}
inline const std::string& ChatMessagePayload::sender_username() const {
  // @@protoc_insertion_point(field_get:chatroom.v7.ChatMessagePayload.sender_username)
  return _internal_sender_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessagePayload::set_sender_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v7.ChatMessagePayload.sender_username)
}
inline std::string* ChatMessagePayload::mutable_sender_username() {
  std::string* _s = _internal_mutable_sender_username();
  // @@protoc_insertion_point(field_mutable:chatroom.v7.ChatMessagePayload.sender_username)
  return _s;
}
inline const std::string& ChatMessagePayload::_internal_sender_username() const {
  return _impl_.sender_username_.Get();
}
inline void ChatMessagePayload::_internal_set_sender_username(const std::string& value) {
  
  _impl_.sender_username_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessagePayload::_internal_mutable_sender_username() {
  
  return _impl_.sender_username_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessagePayload::release_sender_username() {
  // @@protoc_insertion_point(field_release:chatroom.v7.ChatMessagePayload.sender_username)
  return _impl_.sender_username_.Release();
}
inline void ChatMessagePayload::set_allocated_sender_username(std::string* sender_username) {
  if (sender_username != nullptr) {
    
  } else {
    
  }
  _impl_.sender_username_.SetAllocated(sender_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_username_.IsDefault()) {
    _impl_.sender_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v7.ChatMessagePayload.sender_username)
}

// string recipient_username = 3;
inline void ChatMessagePayload::clear_recipient_username() {
  _impl_.recipient_username_.ClearToEmpty();
}
inline const std::string& ChatMessagePayload::recipient_username() const {
  // @@protoc_insertion_point(field_get:chatroom.v7.ChatMessagePayload.recipient_username)
  return _internal_recipient_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessagePayload::set_recipient_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.recipient_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v7.ChatMessagePayload.recipient_username)
}
inline std::string* ChatMessagePayload::mutable_recipient_username() {
  std::string* _s = _internal_mutable_recipient_username();
  // @@protoc_insertion_point(field_mutable:chatroom.v7.ChatMessagePayload.recipient_username)
  return _s;
}
inline const std::string& ChatMessagePayload::_internal_recipient_username() const {
  return _impl_.recipient_username_.Get();
}
inline void ChatMessagePayload::_internal_set_recipient_username(const std::string& value) {
  
  _impl_.recipient_username_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessagePayload::_internal_mutable_recipient_username() {
  
  return _impl_.recipient_username_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessagePayload::release_recipient_username() {
  // @@protoc_insertion_point(field_release:chatroom.v7.ChatMessagePayload.recipient_username)
  return _impl_.recipient_username_.Release();
}
inline void ChatMessagePayload::set_allocated_recipient_username(std::string* recipient_username) {
  if (recipient_username != nullptr) {
    
  } else {
    
  }
  _impl_.recipient_username_.SetAllocated(recipient_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.recipient_username_.IsDefault()) {
    _impl_.recipient_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v7.ChatMessagePayload.recipient_username)
}

// string content = 4;
inline void ChatMessagePayload::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ChatMessagePayload::content() const {
  // @@protoc_insertion_point(field_get:chatroom.v7.ChatMessagePayload.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessagePayload::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v7.ChatMessagePayload.content)
}
inline std::string* ChatMessagePayload::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:chatroom.v7.ChatMessagePayload.content)
  return _s;
}
inline const std::string& ChatMessagePayload::_internal_content() const {
  return _impl_.content_.Get();
}
inline void ChatMessagePayload::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessagePayload::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessagePayload::release_content() {
  // @@protoc_insertion_point(field_release:chatroom.v7.ChatMessagePayload.content)
  return _impl_.content_.Release();
}
inline void ChatMessagePayload::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v7.ChatMessagePayload.content)
}

// int64 created_at_unix_ms = 5;
inline void ChatMessagePayload::clear_created_at_unix_ms() {
  _impl_.created_at_unix_ms_ = int64_t{0};
}
inline int64_t ChatMessagePayload::_internal_created_at_unix_ms() const {
  return _impl_.created_at_unix_ms_;
}
inline int64_t ChatMessagePayload::created_at_unix_ms() const {
  // @@protoc_insertion_point(field_get:chatroom.v7.ChatMessagePayload.created_at_unix_ms)
  return _internal_created_at_unix_ms();
}
inline void ChatMessagePayload::_internal_set_created_at_unix_ms(int64_t value) {
  
  _impl_.created_at_unix_ms_ = value;
}
inline void ChatMessagePayload::set_created_at_unix_ms(int64_t value) {
  _internal_set_created_at_unix_ms(value);
  // @@protoc_insertion_point(field_set:chatroom.v7.ChatMessagePayload.created_at_unix_ms)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v7
}  // namespace chatroom

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chatroom::v7::ChatMessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chatroom::v7::ChatMessageType>() {
  return ::chatroom::v7::ChatMessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chat_5fmessage_2eproto
