// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_file_5ftransfer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_file_5ftransfer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_file_5ftransfer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_file_5ftransfer_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_file_5ftransfer_2eproto;
namespace chatroom {
namespace v9 {
class FileTransferMetadata;
struct FileTransferMetadataDefaultTypeInternal;
extern FileTransferMetadataDefaultTypeInternal _FileTransferMetadata_default_instance_;
class FileUploadResumeState;
struct FileUploadResumeStateDefaultTypeInternal;
extern FileUploadResumeStateDefaultTypeInternal _FileUploadResumeState_default_instance_;
}  // namespace v9
}  // namespace chatroom
PROTOBUF_NAMESPACE_OPEN
template<> ::chatroom::v9::FileTransferMetadata* Arena::CreateMaybeMessage<::chatroom::v9::FileTransferMetadata>(Arena*);
template<> ::chatroom::v9::FileUploadResumeState* Arena::CreateMaybeMessage<::chatroom::v9::FileUploadResumeState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chatroom {
namespace v9 {

enum FileTransferScope : int {
  FILE_TRANSFER_SCOPE_UNSPECIFIED = 0,
  FILE_TRANSFER_PRIVATE = 1,
  FILE_TRANSFER_GROUP = 2,
  FileTransferScope_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  FileTransferScope_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool FileTransferScope_IsValid(int value);
constexpr FileTransferScope FileTransferScope_MIN = FILE_TRANSFER_SCOPE_UNSPECIFIED;
constexpr FileTransferScope FileTransferScope_MAX = FILE_TRANSFER_GROUP;
constexpr int FileTransferScope_ARRAYSIZE = FileTransferScope_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FileTransferScope_descriptor();
template<typename T>
inline const std::string& FileTransferScope_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FileTransferScope>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FileTransferScope_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FileTransferScope_descriptor(), enum_t_value);
}
inline bool FileTransferScope_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FileTransferScope* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FileTransferScope>(
    FileTransferScope_descriptor(), name, value);
}
// ===================================================================

class FileTransferMetadata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chatroom.v9.FileTransferMetadata) */ {
 public:
  inline FileTransferMetadata() : FileTransferMetadata(nullptr) {}
  ~FileTransferMetadata() override;
  explicit PROTOBUF_CONSTEXPR FileTransferMetadata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileTransferMetadata(const FileTransferMetadata& from);
  FileTransferMetadata(FileTransferMetadata&& from) noexcept
    : FileTransferMetadata() {
    *this = ::std::move(from);
  }

  inline FileTransferMetadata& operator=(const FileTransferMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileTransferMetadata& operator=(FileTransferMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileTransferMetadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileTransferMetadata* internal_default_instance() {
    return reinterpret_cast<const FileTransferMetadata*>(
               &_FileTransferMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileTransferMetadata& a, FileTransferMetadata& b) {
    a.Swap(&b);
  }
  inline void Swap(FileTransferMetadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileTransferMetadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileTransferMetadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileTransferMetadata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileTransferMetadata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileTransferMetadata& from) {
    FileTransferMetadata::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileTransferMetadata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chatroom.v9.FileTransferMetadata";
  }
  protected:
  explicit FileTransferMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransferTokenFieldNumber = 1,
    kSenderUsernameFieldNumber = 3,
    kRecipientUsernameFieldNumber = 4,
    kGroupNameFieldNumber = 6,
    kFileNameFieldNumber = 7,
    kSha256HexFieldNumber = 9,
    kStoredRelativePathFieldNumber = 11,
    kGroupIdFieldNumber = 5,
    kFileSizeFieldNumber = 8,
    kCreatedAtUnixMsFieldNumber = 10,
    kScopeFieldNumber = 2,
  };
  // string transfer_token = 1;
  void clear_transfer_token();
  const std::string& transfer_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_transfer_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_transfer_token();
  PROTOBUF_NODISCARD std::string* release_transfer_token();
  void set_allocated_transfer_token(std::string* transfer_token);
  private:
  const std::string& _internal_transfer_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transfer_token(const std::string& value);
  std::string* _internal_mutable_transfer_token();
  public:

  // string sender_username = 3;
  void clear_sender_username();
  const std::string& sender_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_username();
  PROTOBUF_NODISCARD std::string* release_sender_username();
  void set_allocated_sender_username(std::string* sender_username);
  private:
  const std::string& _internal_sender_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_username(const std::string& value);
  std::string* _internal_mutable_sender_username();
  public:

  // string recipient_username = 4;
  void clear_recipient_username();
  const std::string& recipient_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_recipient_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_recipient_username();
  PROTOBUF_NODISCARD std::string* release_recipient_username();
  void set_allocated_recipient_username(std::string* recipient_username);
  private:
  const std::string& _internal_recipient_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_recipient_username(const std::string& value);
  std::string* _internal_mutable_recipient_username();
  public:

  // string group_name = 6;
  void clear_group_name();
  const std::string& group_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_group_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_group_name();
  PROTOBUF_NODISCARD std::string* release_group_name();
  void set_allocated_group_name(std::string* group_name);
  private:
  const std::string& _internal_group_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_group_name(const std::string& value);
  std::string* _internal_mutable_group_name();
  public:

  // string file_name = 7;
  void clear_file_name();
  const std::string& file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* file_name);
  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(const std::string& value);
  std::string* _internal_mutable_file_name();
  public:

  // string sha256_hex = 9;
  void clear_sha256_hex();
  const std::string& sha256_hex() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sha256_hex(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sha256_hex();
  PROTOBUF_NODISCARD std::string* release_sha256_hex();
  void set_allocated_sha256_hex(std::string* sha256_hex);
  private:
  const std::string& _internal_sha256_hex() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sha256_hex(const std::string& value);
  std::string* _internal_mutable_sha256_hex();
  public:

  // string stored_relative_path = 11;
  void clear_stored_relative_path();
  const std::string& stored_relative_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stored_relative_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stored_relative_path();
  PROTOBUF_NODISCARD std::string* release_stored_relative_path();
  void set_allocated_stored_relative_path(std::string* stored_relative_path);
  private:
  const std::string& _internal_stored_relative_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stored_relative_path(const std::string& value);
  std::string* _internal_mutable_stored_relative_path();
  public:

  // uint64 group_id = 5;
  void clear_group_id();
  uint64_t group_id() const;
  void set_group_id(uint64_t value);
  private:
  uint64_t _internal_group_id() const;
  void _internal_set_group_id(uint64_t value);
  public:

  // uint64 file_size = 8;
  void clear_file_size();
  uint64_t file_size() const;
  void set_file_size(uint64_t value);
  private:
  uint64_t _internal_file_size() const;
  void _internal_set_file_size(uint64_t value);
  public:

  // int64 created_at_unix_ms = 10;
  void clear_created_at_unix_ms();
  int64_t created_at_unix_ms() const;
  void set_created_at_unix_ms(int64_t value);
  private:
  int64_t _internal_created_at_unix_ms() const;
  void _internal_set_created_at_unix_ms(int64_t value);
  public:

  // .chatroom.v9.FileTransferScope scope = 2;
  void clear_scope();
  ::chatroom::v9::FileTransferScope scope() const;
  void set_scope(::chatroom::v9::FileTransferScope value);
  private:
  ::chatroom::v9::FileTransferScope _internal_scope() const;
  void _internal_set_scope(::chatroom::v9::FileTransferScope value);
  public:

  // @@protoc_insertion_point(class_scope:chatroom.v9.FileTransferMetadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr transfer_token_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recipient_username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr group_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sha256_hex_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stored_relative_path_;
    uint64_t group_id_;
    uint64_t file_size_;
    int64_t created_at_unix_ms_;
    int scope_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_5ftransfer_2eproto;
};
// -------------------------------------------------------------------

class FileUploadResumeState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chatroom.v9.FileUploadResumeState) */ {
 public:
  inline FileUploadResumeState() : FileUploadResumeState(nullptr) {}
  ~FileUploadResumeState() override;
  explicit PROTOBUF_CONSTEXPR FileUploadResumeState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileUploadResumeState(const FileUploadResumeState& from);
  FileUploadResumeState(FileUploadResumeState&& from) noexcept
    : FileUploadResumeState() {
    *this = ::std::move(from);
  }

  inline FileUploadResumeState& operator=(const FileUploadResumeState& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileUploadResumeState& operator=(FileUploadResumeState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileUploadResumeState& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileUploadResumeState* internal_default_instance() {
    return reinterpret_cast<const FileUploadResumeState*>(
               &_FileUploadResumeState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FileUploadResumeState& a, FileUploadResumeState& b) {
    a.Swap(&b);
  }
  inline void Swap(FileUploadResumeState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileUploadResumeState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileUploadResumeState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileUploadResumeState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileUploadResumeState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileUploadResumeState& from) {
    FileUploadResumeState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileUploadResumeState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chatroom.v9.FileUploadResumeState";
  }
  protected:
  explicit FileUploadResumeState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecipientUsernamesFieldNumber = 2,
    kMetadataFieldNumber = 1,
  };
  // repeated string recipient_usernames = 2;
  int recipient_usernames_size() const;
  private:
  int _internal_recipient_usernames_size() const;
  public:
  void clear_recipient_usernames();
  const std::string& recipient_usernames(int index) const;
  std::string* mutable_recipient_usernames(int index);
  void set_recipient_usernames(int index, const std::string& value);
  void set_recipient_usernames(int index, std::string&& value);
  void set_recipient_usernames(int index, const char* value);
  void set_recipient_usernames(int index, const char* value, size_t size);
  std::string* add_recipient_usernames();
  void add_recipient_usernames(const std::string& value);
  void add_recipient_usernames(std::string&& value);
  void add_recipient_usernames(const char* value);
  void add_recipient_usernames(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& recipient_usernames() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_recipient_usernames();
  private:
  const std::string& _internal_recipient_usernames(int index) const;
  std::string* _internal_add_recipient_usernames();
  public:

  // .chatroom.v9.FileTransferMetadata metadata = 1;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;
  public:
  void clear_metadata();
  const ::chatroom::v9::FileTransferMetadata& metadata() const;
  PROTOBUF_NODISCARD ::chatroom::v9::FileTransferMetadata* release_metadata();
  ::chatroom::v9::FileTransferMetadata* mutable_metadata();
  void set_allocated_metadata(::chatroom::v9::FileTransferMetadata* metadata);
  private:
  const ::chatroom::v9::FileTransferMetadata& _internal_metadata() const;
  ::chatroom::v9::FileTransferMetadata* _internal_mutable_metadata();
  public:
  void unsafe_arena_set_allocated_metadata(
      ::chatroom::v9::FileTransferMetadata* metadata);
  ::chatroom::v9::FileTransferMetadata* unsafe_arena_release_metadata();

  // @@protoc_insertion_point(class_scope:chatroom.v9.FileUploadResumeState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> recipient_usernames_;
    ::chatroom::v9::FileTransferMetadata* metadata_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_5ftransfer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileTransferMetadata

// string transfer_token = 1;
inline void FileTransferMetadata::clear_transfer_token() {
  _impl_.transfer_token_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::transfer_token() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.transfer_token)
  return _internal_transfer_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_transfer_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.transfer_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.transfer_token)
}
inline std::string* FileTransferMetadata::mutable_transfer_token() {
  std::string* _s = _internal_mutable_transfer_token();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.transfer_token)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_transfer_token() const {
  return _impl_.transfer_token_.Get();
}
inline void FileTransferMetadata::_internal_set_transfer_token(const std::string& value) {
  
  _impl_.transfer_token_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_transfer_token() {
  
  return _impl_.transfer_token_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_transfer_token() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.transfer_token)
  return _impl_.transfer_token_.Release();
}
inline void FileTransferMetadata::set_allocated_transfer_token(std::string* transfer_token) {
  if (transfer_token != nullptr) {
    
  } else {
    
  }
  _impl_.transfer_token_.SetAllocated(transfer_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.transfer_token_.IsDefault()) {
    _impl_.transfer_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.transfer_token)
}

// .chatroom.v9.FileTransferScope scope = 2;
inline void FileTransferMetadata::clear_scope() {
  _impl_.scope_ = 0;
}
inline ::chatroom::v9::FileTransferScope FileTransferMetadata::_internal_scope() const {
  return static_cast< ::chatroom::v9::FileTransferScope >(_impl_.scope_);
}
inline ::chatroom::v9::FileTransferScope FileTransferMetadata::scope() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.scope)
  return _internal_scope();
}
inline void FileTransferMetadata::_internal_set_scope(::chatroom::v9::FileTransferScope value) {
  
  _impl_.scope_ = value;
}
inline void FileTransferMetadata::set_scope(::chatroom::v9::FileTransferScope value) {
  _internal_set_scope(value);
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.scope)
}

// string sender_username = 3;
inline void FileTransferMetadata::clear_sender_username() {
  _impl_.sender_username_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::sender_username() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.sender_username)
  return _internal_sender_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_sender_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.sender_username)
}
inline std::string* FileTransferMetadata::mutable_sender_username() {
  std::string* _s = _internal_mutable_sender_username();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.sender_username)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_sender_username() const {
  return _impl_.sender_username_.Get();
}
inline void FileTransferMetadata::_internal_set_sender_username(const std::string& value) {
  
  _impl_.sender_username_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_sender_username() {
  
  return _impl_.sender_username_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_sender_username() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.sender_username)
  return _impl_.sender_username_.Release();
}
inline void FileTransferMetadata::set_allocated_sender_username(std::string* sender_username) {
  if (sender_username != nullptr) {
    
  } else {
    
  }
  _impl_.sender_username_.SetAllocated(sender_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_username_.IsDefault()) {
    _impl_.sender_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.sender_username)
}

// string recipient_username = 4;
inline void FileTransferMetadata::clear_recipient_username() {
  _impl_.recipient_username_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::recipient_username() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.recipient_username)
  return _internal_recipient_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_recipient_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.recipient_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.recipient_username)
}
inline std::string* FileTransferMetadata::mutable_recipient_username() {
  std::string* _s = _internal_mutable_recipient_username();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.recipient_username)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_recipient_username() const {
  return _impl_.recipient_username_.Get();
}
inline void FileTransferMetadata::_internal_set_recipient_username(const std::string& value) {
  
  _impl_.recipient_username_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_recipient_username() {
  
  return _impl_.recipient_username_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_recipient_username() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.recipient_username)
  return _impl_.recipient_username_.Release();
}
inline void FileTransferMetadata::set_allocated_recipient_username(std::string* recipient_username) {
  if (recipient_username != nullptr) {
    
  } else {
    
  }
  _impl_.recipient_username_.SetAllocated(recipient_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.recipient_username_.IsDefault()) {
    _impl_.recipient_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.recipient_username)
}

// uint64 group_id = 5;
inline void FileTransferMetadata::clear_group_id() {
  _impl_.group_id_ = uint64_t{0u};
}
inline uint64_t FileTransferMetadata::_internal_group_id() const {
  return _impl_.group_id_;
}
inline uint64_t FileTransferMetadata::group_id() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.group_id)
  return _internal_group_id();
}
inline void FileTransferMetadata::_internal_set_group_id(uint64_t value) {
  
  _impl_.group_id_ = value;
}
inline void FileTransferMetadata::set_group_id(uint64_t value) {
  _internal_set_group_id(value);
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.group_id)
}

// string group_name = 6;
inline void FileTransferMetadata::clear_group_name() {
  _impl_.group_name_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::group_name() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.group_name)
  return _internal_group_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_group_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.group_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.group_name)
}
inline std::string* FileTransferMetadata::mutable_group_name() {
  std::string* _s = _internal_mutable_group_name();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.group_name)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_group_name() const {
  return _impl_.group_name_.Get();
}
inline void FileTransferMetadata::_internal_set_group_name(const std::string& value) {
  
  _impl_.group_name_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_group_name() {
  
  return _impl_.group_name_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_group_name() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.group_name)
  return _impl_.group_name_.Release();
}
inline void FileTransferMetadata::set_allocated_group_name(std::string* group_name) {
  if (group_name != nullptr) {
    
  } else {
    
  }
  _impl_.group_name_.SetAllocated(group_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.group_name_.IsDefault()) {
    _impl_.group_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.group_name)
}

// string file_name = 7;
inline void FileTransferMetadata::clear_file_name() {
  _impl_.file_name_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::file_name() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.file_name)
  return _internal_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_file_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.file_name)
}
inline std::string* FileTransferMetadata::mutable_file_name() {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.file_name)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_file_name() const {
  return _impl_.file_name_.Get();
}
inline void FileTransferMetadata::_internal_set_file_name(const std::string& value) {
  
  _impl_.file_name_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_file_name() {
  
  return _impl_.file_name_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_file_name() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.file_name)
  return _impl_.file_name_.Release();
}
inline void FileTransferMetadata::set_allocated_file_name(std::string* file_name) {
  if (file_name != nullptr) {
    
  } else {
    
  }
  _impl_.file_name_.SetAllocated(file_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_name_.IsDefault()) {
    _impl_.file_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.file_name)
}

// uint64 file_size = 8;
inline void FileTransferMetadata::clear_file_size() {
  _impl_.file_size_ = uint64_t{0u};
}
inline uint64_t FileTransferMetadata::_internal_file_size() const {
  return _impl_.file_size_;
}
inline uint64_t FileTransferMetadata::file_size() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.file_size)
  return _internal_file_size();
}
inline void FileTransferMetadata::_internal_set_file_size(uint64_t value) {
  
  _impl_.file_size_ = value;
}
inline void FileTransferMetadata::set_file_size(uint64_t value) {
  _internal_set_file_size(value);
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.file_size)
}

// string sha256_hex = 9;
inline void FileTransferMetadata::clear_sha256_hex() {
  _impl_.sha256_hex_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::sha256_hex() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.sha256_hex)
  return _internal_sha256_hex();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_sha256_hex(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sha256_hex_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.sha256_hex)
}
inline std::string* FileTransferMetadata::mutable_sha256_hex() {
  std::string* _s = _internal_mutable_sha256_hex();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.sha256_hex)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_sha256_hex() const {
  return _impl_.sha256_hex_.Get();
}
inline void FileTransferMetadata::_internal_set_sha256_hex(const std::string& value) {
  
  _impl_.sha256_hex_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_sha256_hex() {
  
  return _impl_.sha256_hex_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_sha256_hex() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.sha256_hex)
  return _impl_.sha256_hex_.Release();
}
inline void FileTransferMetadata::set_allocated_sha256_hex(std::string* sha256_hex) {
  if (sha256_hex != nullptr) {
    
  } else {
    
  }
  _impl_.sha256_hex_.SetAllocated(sha256_hex, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sha256_hex_.IsDefault()) {
    _impl_.sha256_hex_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.sha256_hex)
}

// int64 created_at_unix_ms = 10;
inline void FileTransferMetadata::clear_created_at_unix_ms() {
  _impl_.created_at_unix_ms_ = int64_t{0};
}
inline int64_t FileTransferMetadata::_internal_created_at_unix_ms() const {
  return _impl_.created_at_unix_ms_;
}
inline int64_t FileTransferMetadata::created_at_unix_ms() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.created_at_unix_ms)
  return _internal_created_at_unix_ms();
}
inline void FileTransferMetadata::_internal_set_created_at_unix_ms(int64_t value) {
  
  _impl_.created_at_unix_ms_ = value;
}
inline void FileTransferMetadata::set_created_at_unix_ms(int64_t value) {
  _internal_set_created_at_unix_ms(value);
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.created_at_unix_ms)
}

// string stored_relative_path = 11;
inline void FileTransferMetadata::clear_stored_relative_path() {
  _impl_.stored_relative_path_.ClearToEmpty();
}
inline const std::string& FileTransferMetadata::stored_relative_path() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileTransferMetadata.stored_relative_path)
  return _internal_stored_relative_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTransferMetadata::set_stored_relative_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stored_relative_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.v9.FileTransferMetadata.stored_relative_path)
}
inline std::string* FileTransferMetadata::mutable_stored_relative_path() {
  std::string* _s = _internal_mutable_stored_relative_path();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileTransferMetadata.stored_relative_path)
  return _s;
}
inline const std::string& FileTransferMetadata::_internal_stored_relative_path() const {
  return _impl_.stored_relative_path_.Get();
}
inline void FileTransferMetadata::_internal_set_stored_relative_path(const std::string& value) {
  
  _impl_.stored_relative_path_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::_internal_mutable_stored_relative_path() {
  
  return _impl_.stored_relative_path_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTransferMetadata::release_stored_relative_path() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileTransferMetadata.stored_relative_path)
  return _impl_.stored_relative_path_.Release();
}
inline void FileTransferMetadata::set_allocated_stored_relative_path(std::string* stored_relative_path) {
  if (stored_relative_path != nullptr) {
    
  } else {
    
  }
  _impl_.stored_relative_path_.SetAllocated(stored_relative_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stored_relative_path_.IsDefault()) {
    _impl_.stored_relative_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileTransferMetadata.stored_relative_path)
}

// -------------------------------------------------------------------

// FileUploadResumeState

// .chatroom.v9.FileTransferMetadata metadata = 1;
inline bool FileUploadResumeState::_internal_has_metadata() const {
  return this != internal_default_instance() && _impl_.metadata_ != nullptr;
}
inline bool FileUploadResumeState::has_metadata() const {
  return _internal_has_metadata();
}
inline void FileUploadResumeState::clear_metadata() {
  if (GetArenaForAllocation() == nullptr && _impl_.metadata_ != nullptr) {
    delete _impl_.metadata_;
  }
  _impl_.metadata_ = nullptr;
}
inline const ::chatroom::v9::FileTransferMetadata& FileUploadResumeState::_internal_metadata() const {
  const ::chatroom::v9::FileTransferMetadata* p = _impl_.metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::chatroom::v9::FileTransferMetadata&>(
      ::chatroom::v9::_FileTransferMetadata_default_instance_);
}
inline const ::chatroom::v9::FileTransferMetadata& FileUploadResumeState::metadata() const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileUploadResumeState.metadata)
  return _internal_metadata();
}
inline void FileUploadResumeState::unsafe_arena_set_allocated_metadata(
    ::chatroom::v9::FileTransferMetadata* metadata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.metadata_);
  }
  _impl_.metadata_ = metadata;
  if (metadata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chatroom.v9.FileUploadResumeState.metadata)
}
inline ::chatroom::v9::FileTransferMetadata* FileUploadResumeState::release_metadata() {
  
  ::chatroom::v9::FileTransferMetadata* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chatroom::v9::FileTransferMetadata* FileUploadResumeState::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_release:chatroom.v9.FileUploadResumeState.metadata)
  
  ::chatroom::v9::FileTransferMetadata* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
  return temp;
}
inline ::chatroom::v9::FileTransferMetadata* FileUploadResumeState::_internal_mutable_metadata() {
  
  if (_impl_.metadata_ == nullptr) {
    auto* p = CreateMaybeMessage<::chatroom::v9::FileTransferMetadata>(GetArenaForAllocation());
    _impl_.metadata_ = p;
  }
  return _impl_.metadata_;
}
inline ::chatroom::v9::FileTransferMetadata* FileUploadResumeState::mutable_metadata() {
  ::chatroom::v9::FileTransferMetadata* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileUploadResumeState.metadata)
  return _msg;
}
inline void FileUploadResumeState::set_allocated_metadata(::chatroom::v9::FileTransferMetadata* metadata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.metadata_;
  }
  if (metadata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(metadata);
    if (message_arena != submessage_arena) {
      metadata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, metadata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.metadata_ = metadata;
  // @@protoc_insertion_point(field_set_allocated:chatroom.v9.FileUploadResumeState.metadata)
}

// repeated string recipient_usernames = 2;
inline int FileUploadResumeState::_internal_recipient_usernames_size() const {
  return _impl_.recipient_usernames_.size();
}
inline int FileUploadResumeState::recipient_usernames_size() const {
  return _internal_recipient_usernames_size();
}
inline void FileUploadResumeState::clear_recipient_usernames() {
  _impl_.recipient_usernames_.Clear();
}
inline std::string* FileUploadResumeState::add_recipient_usernames() {
  std::string* _s = _internal_add_recipient_usernames();
  // @@protoc_insertion_point(field_add_mutable:chatroom.v9.FileUploadResumeState.recipient_usernames)
  return _s;
}
inline const std::string& FileUploadResumeState::_internal_recipient_usernames(int index) const {
  return _impl_.recipient_usernames_.Get(index);
}
inline const std::string& FileUploadResumeState::recipient_usernames(int index) const {
  // @@protoc_insertion_point(field_get:chatroom.v9.FileUploadResumeState.recipient_usernames)
  return _internal_recipient_usernames(index);
}
inline std::string* FileUploadResumeState::mutable_recipient_usernames(int index) {
  // @@protoc_insertion_point(field_mutable:chatroom.v9.FileUploadResumeState.recipient_usernames)
  return _impl_.recipient_usernames_.Mutable(index);
}
inline void FileUploadResumeState::set_recipient_usernames(int index, const std::string& value) {
  _impl_.recipient_usernames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline void FileUploadResumeState::set_recipient_usernames(int index, std::string&& value) {
  _impl_.recipient_usernames_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline void FileUploadResumeState::set_recipient_usernames(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.recipient_usernames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline void FileUploadResumeState::set_recipient_usernames(int index, const char* value, size_t size) {
  _impl_.recipient_usernames_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline std::string* FileUploadResumeState::_internal_add_recipient_usernames() {
  return _impl_.recipient_usernames_.Add();
}
inline void FileUploadResumeState::add_recipient_usernames(const std::string& value) {
  _impl_.recipient_usernames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline void FileUploadResumeState::add_recipient_usernames(std::string&& value) {
  _impl_.recipient_usernames_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline void FileUploadResumeState::add_recipient_usernames(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.recipient_usernames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline void FileUploadResumeState::add_recipient_usernames(const char* value, size_t size) {
  _impl_.recipient_usernames_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:chatroom.v9.FileUploadResumeState.recipient_usernames)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
FileUploadResumeState::recipient_usernames() const {
  // @@protoc_insertion_point(field_list:chatroom.v9.FileUploadResumeState.recipient_usernames)
  return _impl_.recipient_usernames_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
FileUploadResumeState::mutable_recipient_usernames() {
  // @@protoc_insertion_point(field_mutable_list:chatroom.v9.FileUploadResumeState.recipient_usernames)
  return &_impl_.recipient_usernames_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v9
}  // namespace chatroom

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chatroom::v9::FileTransferScope> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chatroom::v9::FileTransferScope>() {
  return ::chatroom::v9::FileTransferScope_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_file_5ftransfer_2eproto
