// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer.proto

#include "file_transfer.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace chatroom {
namespace v9 {
PROTOBUF_CONSTEXPR FileTransferMetadata::FileTransferMetadata(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.transfer_token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sender_username_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.recipient_username_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.group_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.file_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sha256_hex_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stored_relative_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.group_id_)*/uint64_t{0u}
  , /*decltype(_impl_.file_size_)*/uint64_t{0u}
  , /*decltype(_impl_.created_at_unix_ms_)*/int64_t{0}
  , /*decltype(_impl_.scope_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileTransferMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileTransferMetadataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileTransferMetadataDefaultTypeInternal() {}
  union {
    FileTransferMetadata _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileTransferMetadataDefaultTypeInternal _FileTransferMetadata_default_instance_;
PROTOBUF_CONSTEXPR FileUploadResumeState::FileUploadResumeState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.recipient_usernames_)*/{}
  , /*decltype(_impl_.metadata_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileUploadResumeStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileUploadResumeStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileUploadResumeStateDefaultTypeInternal() {}
  union {
    FileUploadResumeState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileUploadResumeStateDefaultTypeInternal _FileUploadResumeState_default_instance_;
}  // namespace v9
}  // namespace chatroom
static ::_pb::Metadata file_level_metadata_file_5ftransfer_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_file_5ftransfer_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_file_5ftransfer_2eproto = nullptr;

const uint32_t TableStruct_file_5ftransfer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.transfer_token_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.scope_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.sender_username_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.recipient_username_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.group_id_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.group_name_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.file_name_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.file_size_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.sha256_hex_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.created_at_unix_ms_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileTransferMetadata, _impl_.stored_relative_path_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileUploadResumeState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileUploadResumeState, _impl_.metadata_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v9::FileUploadResumeState, _impl_.recipient_usernames_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::chatroom::v9::FileTransferMetadata)},
  { 17, -1, -1, sizeof(::chatroom::v9::FileUploadResumeState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::chatroom::v9::_FileTransferMetadata_default_instance_._instance,
  &::chatroom::v9::_FileUploadResumeState_default_instance_._instance,
};

const char descriptor_table_protodef_file_5ftransfer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023file_transfer.proto\022\013chatroom.v9\"\254\002\n\024F"
  "ileTransferMetadata\022\026\n\016transfer_token\030\001 "
  "\001(\t\022-\n\005scope\030\002 \001(\0162\036.chatroom.v9.FileTra"
  "nsferScope\022\027\n\017sender_username\030\003 \001(\t\022\032\n\022r"
  "ecipient_username\030\004 \001(\t\022\020\n\010group_id\030\005 \001("
  "\004\022\022\n\ngroup_name\030\006 \001(\t\022\021\n\tfile_name\030\007 \001(\t"
  "\022\021\n\tfile_size\030\010 \001(\004\022\022\n\nsha256_hex\030\t \001(\t\022"
  "\032\n\022created_at_unix_ms\030\n \001(\003\022\034\n\024stored_re"
  "lative_path\030\013 \001(\t\"i\n\025FileUploadResumeSta"
  "te\0223\n\010metadata\030\001 \001(\0132!.chatroom.v9.FileT"
  "ransferMetadata\022\033\n\023recipient_usernames\030\002"
  " \003(\t*l\n\021FileTransferScope\022#\n\037FILE_TRANSF"
  "ER_SCOPE_UNSPECIFIED\020\000\022\031\n\025FILE_TRANSFER_"
  "PRIVATE\020\001\022\027\n\023FILE_TRANSFER_GROUP\020\002b\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_file_5ftransfer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_file_5ftransfer_2eproto = {
    false, false, 562, descriptor_table_protodef_file_5ftransfer_2eproto,
    "file_transfer.proto",
    &descriptor_table_file_5ftransfer_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_file_5ftransfer_2eproto::offsets,
    file_level_metadata_file_5ftransfer_2eproto, file_level_enum_descriptors_file_5ftransfer_2eproto,
    file_level_service_descriptors_file_5ftransfer_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_file_5ftransfer_2eproto_getter() {
  return &descriptor_table_file_5ftransfer_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_file_5ftransfer_2eproto(&descriptor_table_file_5ftransfer_2eproto);
namespace chatroom {
namespace v9 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FileTransferScope_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_file_5ftransfer_2eproto);
  return file_level_enum_descriptors_file_5ftransfer_2eproto[0];
}
bool FileTransferScope_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class FileTransferMetadata::_Internal {
 public:
};

FileTransferMetadata::FileTransferMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chatroom.v9.FileTransferMetadata)
}
FileTransferMetadata::FileTransferMetadata(const FileTransferMetadata& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileTransferMetadata* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.transfer_token_){}
    , decltype(_impl_.sender_username_){}
    , decltype(_impl_.recipient_username_){}
    , decltype(_impl_.group_name_){}
    , decltype(_impl_.file_name_){}
    , decltype(_impl_.sha256_hex_){}
    , decltype(_impl_.stored_relative_path_){}
    , decltype(_impl_.group_id_){}
    , decltype(_impl_.file_size_){}
    , decltype(_impl_.created_at_unix_ms_){}
    , decltype(_impl_.scope_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.transfer_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.transfer_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_transfer_token().empty()) {
    _this->_impl_.transfer_token_.Set(from._internal_transfer_token(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sender_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sender_username().empty()) {
    _this->_impl_.sender_username_.Set(from._internal_sender_username(), 
      _this->GetArenaForAllocation());
  }
  _impl_.recipient_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recipient_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_recipient_username().empty()) {
    _this->_impl_.recipient_username_.Set(from._internal_recipient_username(), 
      _this->GetArenaForAllocation());
  }
  _impl_.group_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.group_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_group_name().empty()) {
    _this->_impl_.group_name_.Set(from._internal_group_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_file_name().empty()) {
    _this->_impl_.file_name_.Set(from._internal_file_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sha256_hex_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sha256_hex_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sha256_hex().empty()) {
    _this->_impl_.sha256_hex_.Set(from._internal_sha256_hex(), 
      _this->GetArenaForAllocation());
  }
  _impl_.stored_relative_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stored_relative_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stored_relative_path().empty()) {
    _this->_impl_.stored_relative_path_.Set(from._internal_stored_relative_path(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.group_id_, &from._impl_.group_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.scope_) -
    reinterpret_cast<char*>(&_impl_.group_id_)) + sizeof(_impl_.scope_));
  // @@protoc_insertion_point(copy_constructor:chatroom.v9.FileTransferMetadata)
}

inline void FileTransferMetadata::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.transfer_token_){}
    , decltype(_impl_.sender_username_){}
    , decltype(_impl_.recipient_username_){}
    , decltype(_impl_.group_name_){}
    , decltype(_impl_.file_name_){}
    , decltype(_impl_.sha256_hex_){}
    , decltype(_impl_.stored_relative_path_){}
    , decltype(_impl_.group_id_){uint64_t{0u}}
    , decltype(_impl_.file_size_){uint64_t{0u}}
    , decltype(_impl_.created_at_unix_ms_){int64_t{0}}
    , decltype(_impl_.scope_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.transfer_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.transfer_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sender_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.recipient_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recipient_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.group_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.group_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sha256_hex_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sha256_hex_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.stored_relative_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stored_relative_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FileTransferMetadata::~FileTransferMetadata() {
  // @@protoc_insertion_point(destructor:chatroom.v9.FileTransferMetadata)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileTransferMetadata::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.transfer_token_.Destroy();
  _impl_.sender_username_.Destroy();
  _impl_.recipient_username_.Destroy();
  _impl_.group_name_.Destroy();
  _impl_.file_name_.Destroy();
  _impl_.sha256_hex_.Destroy();
  _impl_.stored_relative_path_.Destroy();
}

void FileTransferMetadata::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileTransferMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:chatroom.v9.FileTransferMetadata)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.transfer_token_.ClearToEmpty();
  _impl_.sender_username_.ClearToEmpty();
  _impl_.recipient_username_.ClearToEmpty();
  _impl_.group_name_.ClearToEmpty();
  _impl_.file_name_.ClearToEmpty();
  _impl_.sha256_hex_.ClearToEmpty();
  _impl_.stored_relative_path_.ClearToEmpty();
  ::memset(&_impl_.group_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.scope_) -
      reinterpret_cast<char*>(&_impl_.group_id_)) + sizeof(_impl_.scope_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileTransferMetadata::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string transfer_token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_transfer_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.transfer_token"));
        } else
          goto handle_unusual;
        continue;
      // .chatroom.v9.FileTransferScope scope = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_scope(static_cast<::chatroom::v9::FileTransferScope>(val));
        } else
          goto handle_unusual;
        continue;
      // string sender_username = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_sender_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.sender_username"));
        } else
          goto handle_unusual;
        continue;
      // string recipient_username = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_recipient_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.recipient_username"));
        } else
          goto handle_unusual;
        continue;
      // uint64 group_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.group_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string group_name = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_group_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.group_name"));
        } else
          goto handle_unusual;
        continue;
      // string file_name = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_file_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.file_name"));
        } else
          goto handle_unusual;
        continue;
      // uint64 file_size = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.file_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string sha256_hex = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_sha256_hex();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.sha256_hex"));
        } else
          goto handle_unusual;
        continue;
      // int64 created_at_unix_ms = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.created_at_unix_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string stored_relative_path = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_stored_relative_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileTransferMetadata.stored_relative_path"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FileTransferMetadata::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chatroom.v9.FileTransferMetadata)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string transfer_token = 1;
  if (!this->_internal_transfer_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_transfer_token().data(), static_cast<int>(this->_internal_transfer_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.transfer_token");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_transfer_token(), target);
  }

  // .chatroom.v9.FileTransferScope scope = 2;
  if (this->_internal_scope() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_scope(), target);
  }

  // string sender_username = 3;
  if (!this->_internal_sender_username().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sender_username().data(), static_cast<int>(this->_internal_sender_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.sender_username");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_sender_username(), target);
  }

  // string recipient_username = 4;
  if (!this->_internal_recipient_username().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_recipient_username().data(), static_cast<int>(this->_internal_recipient_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.recipient_username");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_recipient_username(), target);
  }

  // uint64 group_id = 5;
  if (this->_internal_group_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_group_id(), target);
  }

  // string group_name = 6;
  if (!this->_internal_group_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_group_name().data(), static_cast<int>(this->_internal_group_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.group_name");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_group_name(), target);
  }

  // string file_name = 7;
  if (!this->_internal_file_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_file_name().data(), static_cast<int>(this->_internal_file_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.file_name");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_file_name(), target);
  }

  // uint64 file_size = 8;
  if (this->_internal_file_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(8, this->_internal_file_size(), target);
  }

  // string sha256_hex = 9;
  if (!this->_internal_sha256_hex().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sha256_hex().data(), static_cast<int>(this->_internal_sha256_hex().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.sha256_hex");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_sha256_hex(), target);
  }

  // int64 created_at_unix_ms = 10;
  if (this->_internal_created_at_unix_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(10, this->_internal_created_at_unix_ms(), target);
  }

  // string stored_relative_path = 11;
  if (!this->_internal_stored_relative_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stored_relative_path().data(), static_cast<int>(this->_internal_stored_relative_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileTransferMetadata.stored_relative_path");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_stored_relative_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chatroom.v9.FileTransferMetadata)
  return target;
}

size_t FileTransferMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chatroom.v9.FileTransferMetadata)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string transfer_token = 1;
  if (!this->_internal_transfer_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_transfer_token());
  }

  // string sender_username = 3;
  if (!this->_internal_sender_username().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sender_username());
  }

  // string recipient_username = 4;
  if (!this->_internal_recipient_username().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_recipient_username());
  }

  // string group_name = 6;
  if (!this->_internal_group_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_group_name());
  }

  // string file_name = 7;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_file_name());
  }

  // string sha256_hex = 9;
  if (!this->_internal_sha256_hex().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sha256_hex());
  }

  // string stored_relative_path = 11;
  if (!this->_internal_stored_relative_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stored_relative_path());
  }

  // uint64 group_id = 5;
  if (this->_internal_group_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_group_id());
  }

  // uint64 file_size = 8;
  if (this->_internal_file_size() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_file_size());
  }

  // int64 created_at_unix_ms = 10;
  if (this->_internal_created_at_unix_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_created_at_unix_ms());
  }

  // .chatroom.v9.FileTransferScope scope = 2;
  if (this->_internal_scope() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_scope());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FileTransferMetadata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FileTransferMetadata::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FileTransferMetadata::GetClassData() const { return &_class_data_; }


void FileTransferMetadata::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FileTransferMetadata*>(&to_msg);
  auto& from = static_cast<const FileTransferMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chatroom.v9.FileTransferMetadata)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_transfer_token().empty()) {
    _this->_internal_set_transfer_token(from._internal_transfer_token());
  }
  if (!from._internal_sender_username().empty()) {
    _this->_internal_set_sender_username(from._internal_sender_username());
  }
  if (!from._internal_recipient_username().empty()) {
    _this->_internal_set_recipient_username(from._internal_recipient_username());
  }
  if (!from._internal_group_name().empty()) {
    _this->_internal_set_group_name(from._internal_group_name());
  }
  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  if (!from._internal_sha256_hex().empty()) {
    _this->_internal_set_sha256_hex(from._internal_sha256_hex());
  }
  if (!from._internal_stored_relative_path().empty()) {
    _this->_internal_set_stored_relative_path(from._internal_stored_relative_path());
  }
  if (from._internal_group_id() != 0) {
    _this->_internal_set_group_id(from._internal_group_id());
  }
  if (from._internal_file_size() != 0) {
    _this->_internal_set_file_size(from._internal_file_size());
  }
  if (from._internal_created_at_unix_ms() != 0) {
    _this->_internal_set_created_at_unix_ms(from._internal_created_at_unix_ms());
  }
  if (from._internal_scope() != 0) {
    _this->_internal_set_scope(from._internal_scope());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FileTransferMetadata::CopyFrom(const FileTransferMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chatroom.v9.FileTransferMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileTransferMetadata::IsInitialized() const {
  return true;
}

void FileTransferMetadata::InternalSwap(FileTransferMetadata* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.transfer_token_, lhs_arena,
      &other->_impl_.transfer_token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sender_username_, lhs_arena,
      &other->_impl_.sender_username_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.recipient_username_, lhs_arena,
      &other->_impl_.recipient_username_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.group_name_, lhs_arena,
      &other->_impl_.group_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.file_name_, lhs_arena,
      &other->_impl_.file_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sha256_hex_, lhs_arena,
      &other->_impl_.sha256_hex_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stored_relative_path_, lhs_arena,
      &other->_impl_.stored_relative_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileTransferMetadata, _impl_.scope_)
      + sizeof(FileTransferMetadata::_impl_.scope_)
      - PROTOBUF_FIELD_OFFSET(FileTransferMetadata, _impl_.group_id_)>(
          reinterpret_cast<char*>(&_impl_.group_id_),
          reinterpret_cast<char*>(&other->_impl_.group_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FileTransferMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_file_5ftransfer_2eproto_getter, &descriptor_table_file_5ftransfer_2eproto_once,
      file_level_metadata_file_5ftransfer_2eproto[0]);
}

// ===================================================================

class FileUploadResumeState::_Internal {
 public:
  static const ::chatroom::v9::FileTransferMetadata& metadata(const FileUploadResumeState* msg);
};

const ::chatroom::v9::FileTransferMetadata&
FileUploadResumeState::_Internal::metadata(const FileUploadResumeState* msg) {
  return *msg->_impl_.metadata_;
}
FileUploadResumeState::FileUploadResumeState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chatroom.v9.FileUploadResumeState)
}
FileUploadResumeState::FileUploadResumeState(const FileUploadResumeState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileUploadResumeState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.recipient_usernames_){from._impl_.recipient_usernames_}
    , decltype(_impl_.metadata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_metadata()) {
    _this->_impl_.metadata_ = new ::chatroom::v9::FileTransferMetadata(*from._impl_.metadata_);
  }
  // @@protoc_insertion_point(copy_constructor:chatroom.v9.FileUploadResumeState)
}

inline void FileUploadResumeState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.recipient_usernames_){arena}
    , decltype(_impl_.metadata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FileUploadResumeState::~FileUploadResumeState() {
  // @@protoc_insertion_point(destructor:chatroom.v9.FileUploadResumeState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileUploadResumeState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.recipient_usernames_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.metadata_;
}

void FileUploadResumeState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileUploadResumeState::Clear() {
// @@protoc_insertion_point(message_clear_start:chatroom.v9.FileUploadResumeState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.recipient_usernames_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.metadata_ != nullptr) {
    delete _impl_.metadata_;
  }
  _impl_.metadata_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileUploadResumeState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .chatroom.v9.FileTransferMetadata metadata = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_metadata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string recipient_usernames = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_recipient_usernames();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "chatroom.v9.FileUploadResumeState.recipient_usernames"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FileUploadResumeState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chatroom.v9.FileUploadResumeState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .chatroom.v9.FileTransferMetadata metadata = 1;
  if (this->_internal_has_metadata()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::metadata(this),
        _Internal::metadata(this).GetCachedSize(), target, stream);
  }

  // repeated string recipient_usernames = 2;
  for (int i = 0, n = this->_internal_recipient_usernames_size(); i < n; i++) {
    const auto& s = this->_internal_recipient_usernames(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v9.FileUploadResumeState.recipient_usernames");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chatroom.v9.FileUploadResumeState)
  return target;
}

size_t FileUploadResumeState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chatroom.v9.FileUploadResumeState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string recipient_usernames = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.recipient_usernames_.size());
  for (int i = 0, n = _impl_.recipient_usernames_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.recipient_usernames_.Get(i));
  }

  // .chatroom.v9.FileTransferMetadata metadata = 1;
  if (this->_internal_has_metadata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.metadata_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FileUploadResumeState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FileUploadResumeState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FileUploadResumeState::GetClassData() const { return &_class_data_; }


void FileUploadResumeState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FileUploadResumeState*>(&to_msg);
  auto& from = static_cast<const FileUploadResumeState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chatroom.v9.FileUploadResumeState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.recipient_usernames_.MergeFrom(from._impl_.recipient_usernames_);
  if (from._internal_has_metadata()) {
    _this->_internal_mutable_metadata()->::chatroom::v9::FileTransferMetadata::MergeFrom(
        from._internal_metadata());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FileUploadResumeState::CopyFrom(const FileUploadResumeState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chatroom.v9.FileUploadResumeState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileUploadResumeState::IsInitialized() const {
  return true;
}

void FileUploadResumeState::InternalSwap(FileUploadResumeState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.recipient_usernames_.InternalSwap(&other->_impl_.recipient_usernames_);
  swap(_impl_.metadata_, other->_impl_.metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FileUploadResumeState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_file_5ftransfer_2eproto_getter, &descriptor_table_file_5ftransfer_2eproto_once,
      file_level_metadata_file_5ftransfer_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v9
}  // namespace chatroom
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::chatroom::v9::FileTransferMetadata*
Arena::CreateMaybeMessage< ::chatroom::v9::FileTransferMetadata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chatroom::v9::FileTransferMetadata >(arena);
}
template<> PROTOBUF_NOINLINE ::chatroom::v9::FileUploadResumeState*
Arena::CreateMaybeMessage< ::chatroom::v9::FileUploadResumeState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chatroom::v9::FileUploadResumeState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
