// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend_event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_friend_5fevent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_friend_5fevent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_friend_5fevent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_friend_5fevent_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_friend_5fevent_2eproto;
namespace chatroom {
namespace proto {
class FriendEvent;
struct FriendEventDefaultTypeInternal;
extern FriendEventDefaultTypeInternal _FriendEvent_default_instance_;
}  // namespace proto
}  // namespace chatroom
PROTOBUF_NAMESPACE_OPEN
template<> ::chatroom::proto::FriendEvent* Arena::CreateMaybeMessage<::chatroom::proto::FriendEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chatroom {
namespace proto {

enum FriendEventType : int {
  FRIEND_EVENT_TYPE_UNSPECIFIED = 0,
  FRIEND_REQUEST_SENT = 1,
  FRIEND_REQUEST_ACCEPTED = 2,
  FRIEND_REQUEST_REJECTED = 3,
  FRIEND_REMOVED = 4,
  FriendEventType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  FriendEventType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool FriendEventType_IsValid(int value);
constexpr FriendEventType FriendEventType_MIN = FRIEND_EVENT_TYPE_UNSPECIFIED;
constexpr FriendEventType FriendEventType_MAX = FRIEND_REMOVED;
constexpr int FriendEventType_ARRAYSIZE = FriendEventType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FriendEventType_descriptor();
template<typename T>
inline const std::string& FriendEventType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FriendEventType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FriendEventType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FriendEventType_descriptor(), enum_t_value);
}
inline bool FriendEventType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FriendEventType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FriendEventType>(
    FriendEventType_descriptor(), name, value);
}
// ===================================================================

class FriendEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chatroom.proto.FriendEvent) */ {
 public:
  inline FriendEvent() : FriendEvent(nullptr) {}
  ~FriendEvent() override;
  explicit PROTOBUF_CONSTEXPR FriendEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FriendEvent(const FriendEvent& from);
  FriendEvent(FriendEvent&& from) noexcept
    : FriendEvent() {
    *this = ::std::move(from);
  }

  inline FriendEvent& operator=(const FriendEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline FriendEvent& operator=(FriendEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FriendEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const FriendEvent* internal_default_instance() {
    return reinterpret_cast<const FriendEvent*>(
               &_FriendEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FriendEvent& a, FriendEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(FriendEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FriendEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FriendEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FriendEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FriendEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FriendEvent& from) {
    FriendEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FriendEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chatroom.proto.FriendEvent";
  }
  protected:
  explicit FriendEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActorUsernameFieldNumber = 2,
    kTargetUsernameFieldNumber = 3,
    kOccurredAtUnixMsFieldNumber = 4,
    kTypeFieldNumber = 1,
  };
  // string actor_username = 2;
  void clear_actor_username();
  const std::string& actor_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_actor_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_actor_username();
  PROTOBUF_NODISCARD std::string* release_actor_username();
  void set_allocated_actor_username(std::string* actor_username);
  private:
  const std::string& _internal_actor_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_actor_username(const std::string& value);
  std::string* _internal_mutable_actor_username();
  public:

  // string target_username = 3;
  void clear_target_username();
  const std::string& target_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_target_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_target_username();
  PROTOBUF_NODISCARD std::string* release_target_username();
  void set_allocated_target_username(std::string* target_username);
  private:
  const std::string& _internal_target_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target_username(const std::string& value);
  std::string* _internal_mutable_target_username();
  public:

  // int64 occurred_at_unix_ms = 4;
  void clear_occurred_at_unix_ms();
  int64_t occurred_at_unix_ms() const;
  void set_occurred_at_unix_ms(int64_t value);
  private:
  int64_t _internal_occurred_at_unix_ms() const;
  void _internal_set_occurred_at_unix_ms(int64_t value);
  public:

  // .chatroom.proto.FriendEventType type = 1;
  void clear_type();
  ::chatroom::proto::FriendEventType type() const;
  void set_type(::chatroom::proto::FriendEventType value);
  private:
  ::chatroom::proto::FriendEventType _internal_type() const;
  void _internal_set_type(::chatroom::proto::FriendEventType value);
  public:

  // @@protoc_insertion_point(class_scope:chatroom.proto.FriendEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr actor_username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target_username_;
    int64_t occurred_at_unix_ms_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_friend_5fevent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FriendEvent

// .chatroom.proto.FriendEventType type = 1;
inline void FriendEvent::clear_type() {
  _impl_.type_ = 0;
}
inline ::chatroom::proto::FriendEventType FriendEvent::_internal_type() const {
  return static_cast< ::chatroom::proto::FriendEventType >(_impl_.type_);
}
inline ::chatroom::proto::FriendEventType FriendEvent::type() const {
  // @@protoc_insertion_point(field_get:chatroom.proto.FriendEvent.type)
  return _internal_type();
}
inline void FriendEvent::_internal_set_type(::chatroom::proto::FriendEventType value) {
  
  _impl_.type_ = value;
}
inline void FriendEvent::set_type(::chatroom::proto::FriendEventType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:chatroom.proto.FriendEvent.type)
}

// string actor_username = 2;
inline void FriendEvent::clear_actor_username() {
  _impl_.actor_username_.ClearToEmpty();
}
inline const std::string& FriendEvent::actor_username() const {
  // @@protoc_insertion_point(field_get:chatroom.proto.FriendEvent.actor_username)
  return _internal_actor_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FriendEvent::set_actor_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.actor_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.proto.FriendEvent.actor_username)
}
inline std::string* FriendEvent::mutable_actor_username() {
  std::string* _s = _internal_mutable_actor_username();
  // @@protoc_insertion_point(field_mutable:chatroom.proto.FriendEvent.actor_username)
  return _s;
}
inline const std::string& FriendEvent::_internal_actor_username() const {
  return _impl_.actor_username_.Get();
}
inline void FriendEvent::_internal_set_actor_username(const std::string& value) {
  
  _impl_.actor_username_.Set(value, GetArenaForAllocation());
}
inline std::string* FriendEvent::_internal_mutable_actor_username() {
  
  return _impl_.actor_username_.Mutable(GetArenaForAllocation());
}
inline std::string* FriendEvent::release_actor_username() {
  // @@protoc_insertion_point(field_release:chatroom.proto.FriendEvent.actor_username)
  return _impl_.actor_username_.Release();
}
inline void FriendEvent::set_allocated_actor_username(std::string* actor_username) {
  if (actor_username != nullptr) {
    
  } else {
    
  }
  _impl_.actor_username_.SetAllocated(actor_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.actor_username_.IsDefault()) {
    _impl_.actor_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.proto.FriendEvent.actor_username)
}

// string target_username = 3;
inline void FriendEvent::clear_target_username() {
  _impl_.target_username_.ClearToEmpty();
}
inline const std::string& FriendEvent::target_username() const {
  // @@protoc_insertion_point(field_get:chatroom.proto.FriendEvent.target_username)
  return _internal_target_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FriendEvent::set_target_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.target_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatroom.proto.FriendEvent.target_username)
}
inline std::string* FriendEvent::mutable_target_username() {
  std::string* _s = _internal_mutable_target_username();
  // @@protoc_insertion_point(field_mutable:chatroom.proto.FriendEvent.target_username)
  return _s;
}
inline const std::string& FriendEvent::_internal_target_username() const {
  return _impl_.target_username_.Get();
}
inline void FriendEvent::_internal_set_target_username(const std::string& value) {
  
  _impl_.target_username_.Set(value, GetArenaForAllocation());
}
inline std::string* FriendEvent::_internal_mutable_target_username() {
  
  return _impl_.target_username_.Mutable(GetArenaForAllocation());
}
inline std::string* FriendEvent::release_target_username() {
  // @@protoc_insertion_point(field_release:chatroom.proto.FriendEvent.target_username)
  return _impl_.target_username_.Release();
}
inline void FriendEvent::set_allocated_target_username(std::string* target_username) {
  if (target_username != nullptr) {
    
  } else {
    
  }
  _impl_.target_username_.SetAllocated(target_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.target_username_.IsDefault()) {
    _impl_.target_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatroom.proto.FriendEvent.target_username)
}

// int64 occurred_at_unix_ms = 4;
inline void FriendEvent::clear_occurred_at_unix_ms() {
  _impl_.occurred_at_unix_ms_ = int64_t{0};
}
inline int64_t FriendEvent::_internal_occurred_at_unix_ms() const {
  return _impl_.occurred_at_unix_ms_;
}
inline int64_t FriendEvent::occurred_at_unix_ms() const {
  // @@protoc_insertion_point(field_get:chatroom.proto.FriendEvent.occurred_at_unix_ms)
  return _internal_occurred_at_unix_ms();
}
inline void FriendEvent::_internal_set_occurred_at_unix_ms(int64_t value) {
  
  _impl_.occurred_at_unix_ms_ = value;
}
inline void FriendEvent::set_occurred_at_unix_ms(int64_t value) {
  _internal_set_occurred_at_unix_ms(value);
  // @@protoc_insertion_point(field_set:chatroom.proto.FriendEvent.occurred_at_unix_ms)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace chatroom

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chatroom::proto::FriendEventType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chatroom::proto::FriendEventType>() {
  return ::chatroom::proto::FriendEventType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_friend_5fevent_2eproto
