// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend_event.proto

#include "friend_event.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace chatroom {
namespace v7 {
PROTOBUF_CONSTEXPR FriendEventPayload::FriendEventPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.actor_username_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.target_username_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.occurred_at_unix_ms_)*/int64_t{0}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FriendEventPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FriendEventPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FriendEventPayloadDefaultTypeInternal() {}
  union {
    FriendEventPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FriendEventPayloadDefaultTypeInternal _FriendEventPayload_default_instance_;
}  // namespace v7
}  // namespace chatroom
static ::_pb::Metadata file_level_metadata_friend_5fevent_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_friend_5fevent_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_friend_5fevent_2eproto = nullptr;

const uint32_t TableStruct_friend_5fevent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chatroom::v7::FriendEventPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chatroom::v7::FriendEventPayload, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v7::FriendEventPayload, _impl_.actor_username_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v7::FriendEventPayload, _impl_.target_username_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v7::FriendEventPayload, _impl_.occurred_at_unix_ms_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::chatroom::v7::FriendEventPayload)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::chatroom::v7::_FriendEventPayload_default_instance_._instance,
};

const char descriptor_table_protodef_friend_5fevent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022friend_event.proto\022\013chatroom.v7\"\216\001\n\022Fr"
  "iendEventPayload\022*\n\004type\030\001 \001(\0162\034.chatroo"
  "m.v7.FriendEventType\022\026\n\016actor_username\030\002"
  " \001(\t\022\027\n\017target_username\030\003 \001(\t\022\033\n\023occurre"
  "d_at_unix_ms\030\004 \001(\003*\233\001\n\017FriendEventType\022!"
  "\n\035FRIEND_EVENT_TYPE_UNSPECIFIED\020\000\022\027\n\023FRI"
  "END_REQUEST_SENT\020\001\022\033\n\027FRIEND_REQUEST_ACC"
  "EPTED\020\002\022\033\n\027FRIEND_REQUEST_REJECTED\020\003\022\022\n\016"
  "FRIEND_REMOVED\020\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_friend_5fevent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_friend_5fevent_2eproto = {
    false, false, 344, descriptor_table_protodef_friend_5fevent_2eproto,
    "friend_event.proto",
    &descriptor_table_friend_5fevent_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_friend_5fevent_2eproto::offsets,
    file_level_metadata_friend_5fevent_2eproto, file_level_enum_descriptors_friend_5fevent_2eproto,
    file_level_service_descriptors_friend_5fevent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_friend_5fevent_2eproto_getter() {
  return &descriptor_table_friend_5fevent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_friend_5fevent_2eproto(&descriptor_table_friend_5fevent_2eproto);
namespace chatroom {
namespace v7 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FriendEventType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_friend_5fevent_2eproto);
  return file_level_enum_descriptors_friend_5fevent_2eproto[0];
}
bool FriendEventType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class FriendEventPayload::_Internal {
 public:
};

FriendEventPayload::FriendEventPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chatroom.v7.FriendEventPayload)
}
FriendEventPayload::FriendEventPayload(const FriendEventPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FriendEventPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_username_){}
    , decltype(_impl_.target_username_){}
    , decltype(_impl_.occurred_at_unix_ms_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.actor_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.actor_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_actor_username().empty()) {
    _this->_impl_.actor_username_.Set(from._internal_actor_username(), 
      _this->GetArenaForAllocation());
  }
  _impl_.target_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.target_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_target_username().empty()) {
    _this->_impl_.target_username_.Set(from._internal_target_username(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.occurred_at_unix_ms_, &from._impl_.occurred_at_unix_ms_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.type_) -
    reinterpret_cast<char*>(&_impl_.occurred_at_unix_ms_)) + sizeof(_impl_.type_));
  // @@protoc_insertion_point(copy_constructor:chatroom.v7.FriendEventPayload)
}

inline void FriendEventPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.actor_username_){}
    , decltype(_impl_.target_username_){}
    , decltype(_impl_.occurred_at_unix_ms_){int64_t{0}}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.actor_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.actor_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.target_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.target_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FriendEventPayload::~FriendEventPayload() {
  // @@protoc_insertion_point(destructor:chatroom.v7.FriendEventPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FriendEventPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.actor_username_.Destroy();
  _impl_.target_username_.Destroy();
}

void FriendEventPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FriendEventPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:chatroom.v7.FriendEventPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.actor_username_.ClearToEmpty();
  _impl_.target_username_.ClearToEmpty();
  ::memset(&_impl_.occurred_at_unix_ms_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.occurred_at_unix_ms_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FriendEventPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .chatroom.v7.FriendEventType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::chatroom::v7::FriendEventType>(val));
        } else
          goto handle_unusual;
        continue;
      // string actor_username = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_actor_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v7.FriendEventPayload.actor_username"));
        } else
          goto handle_unusual;
        continue;
      // string target_username = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_target_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v7.FriendEventPayload.target_username"));
        } else
          goto handle_unusual;
        continue;
      // int64 occurred_at_unix_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.occurred_at_unix_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FriendEventPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chatroom.v7.FriendEventPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .chatroom.v7.FriendEventType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // string actor_username = 2;
  if (!this->_internal_actor_username().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_actor_username().data(), static_cast<int>(this->_internal_actor_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v7.FriendEventPayload.actor_username");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_actor_username(), target);
  }

  // string target_username = 3;
  if (!this->_internal_target_username().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_target_username().data(), static_cast<int>(this->_internal_target_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v7.FriendEventPayload.target_username");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_target_username(), target);
  }

  // int64 occurred_at_unix_ms = 4;
  if (this->_internal_occurred_at_unix_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_occurred_at_unix_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chatroom.v7.FriendEventPayload)
  return target;
}

size_t FriendEventPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chatroom.v7.FriendEventPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string actor_username = 2;
  if (!this->_internal_actor_username().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_actor_username());
  }

  // string target_username = 3;
  if (!this->_internal_target_username().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_target_username());
  }

  // int64 occurred_at_unix_ms = 4;
  if (this->_internal_occurred_at_unix_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_occurred_at_unix_ms());
  }

  // .chatroom.v7.FriendEventType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FriendEventPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FriendEventPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FriendEventPayload::GetClassData() const { return &_class_data_; }


void FriendEventPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FriendEventPayload*>(&to_msg);
  auto& from = static_cast<const FriendEventPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chatroom.v7.FriendEventPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_actor_username().empty()) {
    _this->_internal_set_actor_username(from._internal_actor_username());
  }
  if (!from._internal_target_username().empty()) {
    _this->_internal_set_target_username(from._internal_target_username());
  }
  if (from._internal_occurred_at_unix_ms() != 0) {
    _this->_internal_set_occurred_at_unix_ms(from._internal_occurred_at_unix_ms());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FriendEventPayload::CopyFrom(const FriendEventPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chatroom.v7.FriendEventPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FriendEventPayload::IsInitialized() const {
  return true;
}

void FriendEventPayload::InternalSwap(FriendEventPayload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.actor_username_, lhs_arena,
      &other->_impl_.actor_username_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.target_username_, lhs_arena,
      &other->_impl_.target_username_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FriendEventPayload, _impl_.type_)
      + sizeof(FriendEventPayload::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(FriendEventPayload, _impl_.occurred_at_unix_ms_)>(
          reinterpret_cast<char*>(&_impl_.occurred_at_unix_ms_),
          reinterpret_cast<char*>(&other->_impl_.occurred_at_unix_ms_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FriendEventPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_friend_5fevent_2eproto_getter, &descriptor_table_friend_5fevent_2eproto_once,
      file_level_metadata_friend_5fevent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v7
}  // namespace chatroom
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::chatroom::v7::FriendEventPayload*
Arena::CreateMaybeMessage< ::chatroom::v7::FriendEventPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chatroom::v7::FriendEventPayload >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
