// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group_message.proto

#include "group_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace chatroom {
namespace v8 {
PROTOBUF_CONSTEXPR GroupMessagePayload::GroupMessagePayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.group_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sender_username_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.group_id_)*/uint64_t{0u}
  , /*decltype(_impl_.created_at_unix_ms_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GroupMessagePayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GroupMessagePayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GroupMessagePayloadDefaultTypeInternal() {}
  union {
    GroupMessagePayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GroupMessagePayloadDefaultTypeInternal _GroupMessagePayload_default_instance_;
}  // namespace v8
}  // namespace chatroom
static ::_pb::Metadata file_level_metadata_group_5fmessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_group_5fmessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_group_5fmessage_2eproto = nullptr;

const uint32_t TableStruct_group_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chatroom::v8::GroupMessagePayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chatroom::v8::GroupMessagePayload, _impl_.group_id_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v8::GroupMessagePayload, _impl_.group_name_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v8::GroupMessagePayload, _impl_.sender_username_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v8::GroupMessagePayload, _impl_.content_),
  PROTOBUF_FIELD_OFFSET(::chatroom::v8::GroupMessagePayload, _impl_.created_at_unix_ms_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::chatroom::v8::GroupMessagePayload)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::chatroom::v8::_GroupMessagePayload_default_instance_._instance,
};

const char descriptor_table_protodef_group_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023group_message.proto\022\013chatroom.v8\"\201\001\n\023G"
  "roupMessagePayload\022\020\n\010group_id\030\001 \001(\004\022\022\n\n"
  "group_name\030\002 \001(\t\022\027\n\017sender_username\030\003 \001("
  "\t\022\017\n\007content\030\004 \001(\t\022\032\n\022created_at_unix_ms"
  "\030\005 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_group_5fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_group_5fmessage_2eproto = {
    false, false, 174, descriptor_table_protodef_group_5fmessage_2eproto,
    "group_message.proto",
    &descriptor_table_group_5fmessage_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_group_5fmessage_2eproto::offsets,
    file_level_metadata_group_5fmessage_2eproto, file_level_enum_descriptors_group_5fmessage_2eproto,
    file_level_service_descriptors_group_5fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_group_5fmessage_2eproto_getter() {
  return &descriptor_table_group_5fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_group_5fmessage_2eproto(&descriptor_table_group_5fmessage_2eproto);
namespace chatroom {
namespace v8 {

// ===================================================================

class GroupMessagePayload::_Internal {
 public:
};

GroupMessagePayload::GroupMessagePayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chatroom.v8.GroupMessagePayload)
}
GroupMessagePayload::GroupMessagePayload(const GroupMessagePayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GroupMessagePayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.group_name_){}
    , decltype(_impl_.sender_username_){}
    , decltype(_impl_.content_){}
    , decltype(_impl_.group_id_){}
    , decltype(_impl_.created_at_unix_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.group_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.group_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_group_name().empty()) {
    _this->_impl_.group_name_.Set(from._internal_group_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sender_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sender_username().empty()) {
    _this->_impl_.sender_username_.Set(from._internal_sender_username(), 
      _this->GetArenaForAllocation());
  }
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.group_id_, &from._impl_.group_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.created_at_unix_ms_) -
    reinterpret_cast<char*>(&_impl_.group_id_)) + sizeof(_impl_.created_at_unix_ms_));
  // @@protoc_insertion_point(copy_constructor:chatroom.v8.GroupMessagePayload)
}

inline void GroupMessagePayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.group_name_){}
    , decltype(_impl_.sender_username_){}
    , decltype(_impl_.content_){}
    , decltype(_impl_.group_id_){uint64_t{0u}}
    , decltype(_impl_.created_at_unix_ms_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.group_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.group_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sender_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GroupMessagePayload::~GroupMessagePayload() {
  // @@protoc_insertion_point(destructor:chatroom.v8.GroupMessagePayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GroupMessagePayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.group_name_.Destroy();
  _impl_.sender_username_.Destroy();
  _impl_.content_.Destroy();
}

void GroupMessagePayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GroupMessagePayload::Clear() {
// @@protoc_insertion_point(message_clear_start:chatroom.v8.GroupMessagePayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.group_name_.ClearToEmpty();
  _impl_.sender_username_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  ::memset(&_impl_.group_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.created_at_unix_ms_) -
      reinterpret_cast<char*>(&_impl_.group_id_)) + sizeof(_impl_.created_at_unix_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GroupMessagePayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 group_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.group_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string group_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_group_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v8.GroupMessagePayload.group_name"));
        } else
          goto handle_unusual;
        continue;
      // string sender_username = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_sender_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v8.GroupMessagePayload.sender_username"));
        } else
          goto handle_unusual;
        continue;
      // string content = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chatroom.v8.GroupMessagePayload.content"));
        } else
          goto handle_unusual;
        continue;
      // int64 created_at_unix_ms = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.created_at_unix_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GroupMessagePayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chatroom.v8.GroupMessagePayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 group_id = 1;
  if (this->_internal_group_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_group_id(), target);
  }

  // string group_name = 2;
  if (!this->_internal_group_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_group_name().data(), static_cast<int>(this->_internal_group_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v8.GroupMessagePayload.group_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_group_name(), target);
  }

  // string sender_username = 3;
  if (!this->_internal_sender_username().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sender_username().data(), static_cast<int>(this->_internal_sender_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v8.GroupMessagePayload.sender_username");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_sender_username(), target);
  }

  // string content = 4;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chatroom.v8.GroupMessagePayload.content");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_content(), target);
  }

  // int64 created_at_unix_ms = 5;
  if (this->_internal_created_at_unix_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_created_at_unix_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chatroom.v8.GroupMessagePayload)
  return target;
}

size_t GroupMessagePayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chatroom.v8.GroupMessagePayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string group_name = 2;
  if (!this->_internal_group_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_group_name());
  }

  // string sender_username = 3;
  if (!this->_internal_sender_username().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sender_username());
  }

  // string content = 4;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  // uint64 group_id = 1;
  if (this->_internal_group_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_group_id());
  }

  // int64 created_at_unix_ms = 5;
  if (this->_internal_created_at_unix_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_created_at_unix_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GroupMessagePayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GroupMessagePayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GroupMessagePayload::GetClassData() const { return &_class_data_; }


void GroupMessagePayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GroupMessagePayload*>(&to_msg);
  auto& from = static_cast<const GroupMessagePayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chatroom.v8.GroupMessagePayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_group_name().empty()) {
    _this->_internal_set_group_name(from._internal_group_name());
  }
  if (!from._internal_sender_username().empty()) {
    _this->_internal_set_sender_username(from._internal_sender_username());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_group_id() != 0) {
    _this->_internal_set_group_id(from._internal_group_id());
  }
  if (from._internal_created_at_unix_ms() != 0) {
    _this->_internal_set_created_at_unix_ms(from._internal_created_at_unix_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GroupMessagePayload::CopyFrom(const GroupMessagePayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chatroom.v8.GroupMessagePayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroupMessagePayload::IsInitialized() const {
  return true;
}

void GroupMessagePayload::InternalSwap(GroupMessagePayload* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.group_name_, lhs_arena,
      &other->_impl_.group_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sender_username_, lhs_arena,
      &other->_impl_.sender_username_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GroupMessagePayload, _impl_.created_at_unix_ms_)
      + sizeof(GroupMessagePayload::_impl_.created_at_unix_ms_)
      - PROTOBUF_FIELD_OFFSET(GroupMessagePayload, _impl_.group_id_)>(
          reinterpret_cast<char*>(&_impl_.group_id_),
          reinterpret_cast<char*>(&other->_impl_.group_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GroupMessagePayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_group_5fmessage_2eproto_getter, &descriptor_table_group_5fmessage_2eproto_once,
      file_level_metadata_group_5fmessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v8
}  // namespace chatroom
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::chatroom::v8::GroupMessagePayload*
Arena::CreateMaybeMessage< ::chatroom::v8::GroupMessagePayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chatroom::v8::GroupMessagePayload >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
